=== hanb102400/JoooQuick/jooo-quick-retinue/jooo-quick-generator/src/main/resources/generator_1_0.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
- Licensed Text
-->
<!ELEMENT configuration (import*, common, jdbc, templates, modules, tables)>


<!ELEMENT import (property*)>
<!ATTLIST import
        resource CDATA #IMPLIED
        url CDATA #IMPLIED>

<!ELEMENT common (property*)>
<!ATTLIST common
        resource CDATA #IMPLIED
        url CDATA #IMPLIED>

<!ELEMENT jdbc (property*)>
<!ATTLIST jdbc
        driverClassName CDATA #REQUIRED
        url CDATA #REQUIRED
        username CDATA #IMPLIED
        password CDATA #IMPLIED>


<!ELEMENT property EMPTY>
<!ATTLIST property
        name CDATA #REQUIRED
        value CDATA #REQUIRED>


<!ELEMENT templates (template*)>
<!ELEMENT template EMPTY>
<!ATTLIST template
        name CDATA #REQUIRED
        fileName CDATA #REQUIRED
        packageName CDATA #IMPLIED
        type CDATA #IMPLIED >

<!ELEMENT modules (module*)>
<!ELEMENT module EMPTY>
<!ATTLIST module
        name CDATA #IMPLIED
        moduleDir CDATA #REQUIRED
        sources CDATA #IMPLIED
        resources CDATA #IMPLIED
        templates CDATA #IMPLIED
        isSub CDATA #IMPLIED>


<!ELEMENT tables (table*)>
<!ELEMENT table (columnOverride*, columnIgnore*)>
<!ATTLIST table
        tableName CDATA #REQUIRED
        className CDATA #IMPLIED
        subPackageName CDATA #IMPLIED
        catalog CDATA #IMPLIED
        schema CDATA #IMPLIED >

<!ELEMENT columnOverride EMPTY>
<!ATTLIST columnOverride
        column CDATA #REQUIRED
        field CDATA #IMPLIED
        javaType CDATA #IMPLIED
        jdbcType CDATA #IMPLIED
        ignore CDATA #IMPLIED >

<!ELEMENT columnIgnore EMPTY>
<!ATTLIST columnIgnore
        column CDATA #REQUIRED
>

=== hanb102400/JoooQuick/jooo-quick-retinue/jooo-quick-generator/src/main/resources/generator.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE configuration
        PUBLIC "-//rats.org//DTD Lu Generator Configuration 1.0//EN"
        "generator_1_0.dtd">
<configuration>

    <import resource="jdbc.properties"/>

    <common>
        <!-- 工程和模板配置 -->
        <property name="out.dir" value="G:/code/JoooQuick"></property>
        <property name="out.zip" value="false"></property>
        <property name="out.override" value="true"></property>
        <property name="template.dir" value="template/default"></property>
        <property name="template.author" value="@jooo.gen"></property>
        <property name="jdbc.driverClassName" value="${jdbc.driverClassName}"></property>
        <property name="jdbc.url" value="${jdbc.url}"></property>
        <property name="jdbc.username" value="${jdbc.username}"></property>
        <property name="jdbc.password" value="${jdbc.password}"></property>
    </common>

    <!-- 模板文件配置，此处按需自己定制编写 -->
    <templates>
        <template name="entity" packageName="com.shawn.admin.rbac.entity" fileName="${className}.java"/>
        <template name="mapper" packageName="com.shawn.admin.rbac.dao" fileName="${className}Mapper.java"/>
        <template name="dao" packageName="com.shawn.admin.rbac.dao" fileName="${className}Dao.java"/>
        <template name="service" packageName="com.shawn.admin.rbac.service" fileName="${className}Service.java"/>
        <template name="serviceImpl" packageName="com.shawn.admin.rbac.service.impl" fileName="${className}ServiceImpl.java"/>
        <template name="controller" packageName="com.shawn.admin.rbac.controller" fileName="${className}Controller.java"/>
        <template name="xmlMapper" packageName="mybatis.mapper" fileName="${className}Mapper.xml" type="xml"/>
    </templates>


    <!-- 模块配置 -->
    <modules>
        <module moduleDir="jooo-quick-admin"
                sources="src/main/java"
                resources="src/main/resources"
                templates="entity,mapper,service,serviceImpl,controller"

        />
    </modules>


    <!-- 配置需要生成代码的表，tableName：表名; className：类名 ,subPackageName: 子包名称
       <table tableName="tb_user_test" className="UserTest" type="table,tree,option">
            <columnOverride column="testName"
                            field="username"
                            javaType="java.lang.Long"
                            jdbcType="VARCHAR"
                            ignore="true"/>

            <columnOverride column="id" field="id"/>
            <columnOverride column="type" field="atype"/>
            <columnOverride column="username" field="ausername"/>
            <columnOverride column="age" field="age"/>

            <columnIgnore column="password" />
            <columnIgnore column="status"/>

        </table>
    -->
    <!--
     <views>
      <view className="SysDictType" type="table,tree,option" operations="query,add,edit,remove.import,export">
          <form field="id" input="text"  mode="EQ" match="" pages="query,detail,add,edit,list,export"/>
          <form field="atype"  select="text"  mode="EQ" match="" pages="query,detail,add,edit,list,export"/>
      </view>
  </views>
  -->


    <tables>
        <table tableName="sys_dict_type" className="SysDictType"></table>
        <table tableName="sys_dict_data" className="SysDictData"></table>
        <table tableName="sys_depart" className="SysDepart"></table>
        <table tableName="sys_user" className="SysUser"></table>
        <table tableName="sys_role" className="SysRole"></table>
        <table tableName="sys_menu" className="SysMenu"></table>
        <table tableName="sys_user_role" className="SysUserRole"></table>
        <table tableName="sys_role_menu" className="SysRoleMenu"></table>
        <table tableName="sys_login_log" className="SysLoginLog"></table>
        <table tableName="sys_operate_log" className="SysOperateLog"></table>
    </tables>


</configuration>
